#%RAML 1.0
version: v1
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/035a33e2-50cc-41e6-91d5-3ba255a318df/ # 
title: func

/person:
  post:
    body:
      application/json:
    responses:
      200:
        body:
          application/json:
            